version: '3.7'
services:
  db:
    image: postgres:15.5-alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=day06
    ports:
        - '5432:5432'
