
version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.10.4
    container_name: day03-elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false